/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feeds */
        get: operations["get_feeds_feeds_get"];
        put?: never;
        /** Create Feed */
        post: operations["create_feed_feeds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Feed Url */
        post: operations["parse_feed_url_feeds_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Feed */
        post: operations["validate_feed_feeds_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/opml/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Opml File */
        post: operations["import_opml_file_feeds_opml_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/opml/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Opml File */
        get: operations["export_opml_file_feeds_opml_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/sync-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync All */
        post: operations["sync_all_feeds_sync_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feed_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync One */
        post: operations["sync_one_feeds__feed_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feed_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Feed */
        delete: operations["remove_feed_feeds__feed_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clean Content */
        post: operations["clean_content_content_clean_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/entries/{article_id}/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clean Stored Content */
        get: operations["clean_stored_content_content_entries__article_id__clean_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/summary/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Summary
         * @description 生成摘要
         */
        post: operations["generate_summary_agents_summary_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CleanContentRequest */
        CleanContentRequest: {
            /** Raw Html */
            raw_html: string;
            /** Source Url */
            source_url: string;
            /** Article Id */
            article_id?: string | null;
            /** Content Hash */
            content_hash?: string | null;
        };
        /** CleanContentResponse */
        CleanContentResponse: {
            /** Article Id */
            article_id?: string | null;
            /** Cleaned Html */
            cleaned_html: string;
            /** Cleaned Markdown */
            cleaned_markdown: string;
            /** Plain Text */
            plain_text: string;
            /** Content Hash */
            content_hash?: string | null;
            /** Word Count */
            word_count: number;
            /** Reading Time Minutes */
            reading_time_minutes: number;
        };
        /** Feed */
        Feed: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Site Url */
            site_url: string;
            /** Feed Url */
            feed_url: string;
            /** Unread Count */
            unread_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "queued" | "running" | "success" | "failure" | "cancelled";
        };
        /** FeedIssue */
        FeedIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Path
             * @default
             */
            path: string;
        };
        /** FeedValidationResult */
        FeedValidationResult: {
            /** Valid */
            valid: boolean;
            /** Format */
            format: string;
            /** Errors */
            errors?: components["schemas"]["FeedIssue"][];
            /** Warnings */
            warnings?: components["schemas"]["FeedIssue"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OPMLImportResult */
        OPMLImportResult: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors?: components["schemas"]["FeedIssue"][];
            /** Feeds */
            feeds?: components["schemas"]["Feed"][];
        };
        /** ParseFeedRequest */
        ParseFeedRequest: {
            /** Url */
            url: string;
        };
        /** ParsedEntry */
        ParsedEntry: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Author
             * @default
             */
            author: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Published At
             * @default
             */
            published_at: string;
            /**
             * Raw Html
             * @default
             */
            raw_html: string;
        };
        /** ParsedFeed */
        ParsedFeed: {
            /** Title */
            title: string;
            /**
             * Site Url
             * @default
             */
            site_url: string;
            /** Feed Url */
            feed_url: string;
            /** Format */
            format: string;
            /** Entries */
            entries?: components["schemas"]["ParsedEntry"][];
        };
        /** SubscribeFeedRequest */
        SubscribeFeedRequest: {
            /** Url */
            url: string;
            /**
             * Sync
             * @default true
             */
            sync: boolean;
        };
        /** SummaryRequest */
        SummaryRequest: {
            /** Entry Id */
            entry_id: string;
            /**
             * Target Lang
             * @default en
             */
            target_lang: string;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Entry Id */
            entry_id: string;
            /** Summary */
            summary: string;
        };
        /** SyncResult */
        SyncResult: {
            /** Feed Id */
            feed_id: string;
            /** Status */
            status: string;
            /** Fetched */
            fetched: number;
            /** Saved */
            saved: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Not Modified
             * @default false
             */
            not_modified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_feeds_feeds_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feed_feeds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_feed_url_feeds_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_feed_feeds_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedValidationResult"];
                };
            };
        };
    };
    import_opml_file_feeds_opml_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OPMLImportResult"];
                };
            };
        };
    };
    export_opml_file_feeds_opml_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sync_all_feeds_sync_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"][];
                };
            };
        };
    };
    sync_one_feeds__feed_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_feed_feeds__feed_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clean_content_content_clean_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanContentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clean_stored_content_content_entries__article_id__clean_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_summary_agents_summary_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
