/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feeds */
        get: operations["get_feeds_feeds_get"];
        put?: never;
        /** Create Feed */
        post: operations["create_feed_feeds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Feed Url */
        post: operations["parse_feed_url_feeds_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Feed */
        post: operations["validate_feed_feeds_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/opml/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Opml File */
        post: operations["import_opml_file_feeds_opml_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/opml/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Opml File */
        get: operations["export_opml_file_feeds_opml_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/sync-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync All */
        post: operations["sync_all_feeds_sync_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feed_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync One */
        post: operations["sync_one_feeds__feed_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feed_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Feed */
        delete: operations["remove_feed_feeds__feed_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tags */
        get: operations["get_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Providers
         * @description 获取所有提供商列表（不包含敏感信息）
         */
        get: operations["get_providers_providers__get"];
        put?: never;
        /**
         * Create Provider
         * @description 创建新的提供商
         */
        post: operations["create_provider_providers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provider By Name
         * @description 获取指定提供商
         */
        get: operations["get_provider_by_name_providers__name__get"];
        /**
         * Update Provider By Name
         * @description 更新提供商配置
         */
        put: operations["update_provider_by_name_providers__name__put"];
        post?: never;
        /**
         * Delete Provider
         * @description 删除提供商
         */
        delete: operations["delete_provider_providers__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default Provider
         * @description 获取默认提供商
         */
        get: operations["get_default_provider_providers_default_get"];
        put?: never;
        /**
         * Set Default Provider
         * @description 设置默认提供商
         */
        post: operations["set_default_provider_providers_default_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/test/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Provider
         * @description 测试提供商连接
         */
        post: operations["test_provider_providers_test__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entries */
        get: operations["get_entries_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["get_entry_entries__entry_id__get"];
        put?: never;
        post?: never;
        /** Remove Entry */
        delete: operations["remove_entry_entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Entry Read State */
        patch: operations["set_entry_read_state_entries__entry_id__read_patch"];
        trace?: never;
    };
    "/entries/{entry_id}/star": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Entry Star State */
        patch: operations["set_entry_star_state_entries__entry_id__star_patch"];
        trace?: never;
    };
    "/content/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clean Content */
        post: operations["clean_content_content_clean_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/entries/{article_id}/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clean Stored Content */
        get: operations["clean_stored_content_content_entries__article_id__clean_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/entries/{article_id}/web": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Stored Web Page */
        get: operations["fetch_stored_web_page_content_entries__article_id__web_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/summary/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Summary */
        post: operations["generate_summary_agents_summary_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/translation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate Article
         * @description Translate an article to the target language.
         *
         *     The translation is performed using the specified (or default) LLM provider.
         *     Results are persisted to the database.
         *
         *     Request:
         *         {
         *           "entry_id": "article-123",
         *           "target_lang": "English",
         *           "provider": "openai",        # optional, uses default if not specified
         *           "model": "gpt-4"             # optional, uses provider default if not specified
         *         }
         *
         *     Response on success (200):
         *         {
         *           "entry_id": "article-123",
         *           "target_lang": "English",
         *           "translation_html": "Translated content...",
         *           "status": "success",
         *           "provider": "openai",
         *           "model": "gpt-4"
         *         }
         *
         *     Response on translation failure (200 with status: failure):
         *         {
         *           "entry_id": "article-123",
         *           "target_lang": "English",
         *           "translation_html": "",
         *           "status": "failure",
         *           "provider": "openai",
         *           "model": "gpt-4"
         *         }
         *
         *     Error responses:
         *         404: Article not found
         *         409: Article has no content to translate
         *
         *     Args:
         *         request: TranslationRequest with entry_id, target_lang, provider, model
         *
         *     Returns:
         *         TranslationResult with translated content and status
         *
         *     Raises:
         *         HTTPException 404: If article doesn't exist
         *         HTTPException 409: If article has no content
         */
        post: operations["translate_article_agents_translation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CleanContentRequest */
        CleanContentRequest: {
            /** Raw Html */
            raw_html: string;
            /** Source Url */
            source_url: string;
            /** Article Id */
            article_id?: string | null;
            /** Content Hash */
            content_hash?: string | null;
        };
        /** CleanContentResponse */
        CleanContentResponse: {
            /** Article Id */
            article_id?: string | null;
            /** Cleaned Html */
            cleaned_html: string;
            /** Cleaned Markdown */
            cleaned_markdown: string;
            /** Plain Text */
            plain_text: string;
            /** Content Hash */
            content_hash?: string | null;
            /** Word Count */
            word_count: number;
            /** Reading Time Minutes */
            reading_time_minutes: number;
        };
        /** CreateProviderRequest */
        CreateProviderRequest: {
            /** Name */
            name: string;
            /**
             * Kind
             * @default openai_compatible
             */
            kind: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Api Key Header */
            api_key_header?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** Entry */
        Entry: {
            /** Id */
            id: string;
            /** Feed Id */
            feed_id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Author */
            author: string;
            /** Url */
            url: string;
            /** Published At */
            published_at: string;
            /** Is Read */
            is_read: boolean;
            /** Is Starred */
            is_starred: boolean;
            /** Tag Ids */
            tag_ids: string[];
            /** Reader Html */
            reader_html: string;
            /** Web Preview */
            web_preview: string;
            /** Related Entry Ids */
            related_entry_ids: string[];
            /** Note */
            note: string;
            /** Summary Text */
            summary_text: string;
            /** Translation Html */
            translation_html?: string | null;
            /**
             * Translation Status
             * @enum {string}
             */
            translation_status: "idle" | "queued" | "running" | "success" | "failure" | "cancelled";
        };
        /** EntryDeleteResult */
        EntryDeleteResult: {
            /** Entry Id */
            entry_id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** EntryReadStateRequest */
        EntryReadStateRequest: {
            /** Is Read */
            is_read: boolean;
        };
        /** EntryStarStateRequest */
        EntryStarStateRequest: {
            /** Is Starred */
            is_starred: boolean;
        };
        /** Feed */
        Feed: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Site Url */
            site_url: string;
            /** Feed Url */
            feed_url: string;
            /** Unread Count */
            unread_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "queued" | "running" | "success" | "failure" | "cancelled";
        };
        /** FeedIssue */
        FeedIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Path
             * @default
             */
            path: string;
        };
        /** FeedValidationResult */
        FeedValidationResult: {
            /** Valid */
            valid: boolean;
            /** Format */
            format: string;
            /** Errors */
            errors?: components["schemas"]["FeedIssue"][];
            /** Warnings */
            warnings?: components["schemas"]["FeedIssue"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OPMLImportResult */
        OPMLImportResult: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors?: components["schemas"]["FeedIssue"][];
            /** Feeds */
            feeds?: components["schemas"]["Feed"][];
        };
        /** ParseFeedRequest */
        ParseFeedRequest: {
            /** Url */
            url: string;
        };
        /** ParsedEntry */
        ParsedEntry: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Author
             * @default
             */
            author: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Published At
             * @default
             */
            published_at: string;
            /**
             * Raw Html
             * @default
             */
            raw_html: string;
        };
        /** ParsedFeed */
        ParsedFeed: {
            /** Title */
            title: string;
            /**
             * Site Url
             * @default
             */
            site_url: string;
            /** Feed Url */
            feed_url: string;
            /** Format */
            format: string;
            /** Entries */
            entries?: components["schemas"]["ParsedEntry"][];
        };
        /**
         * ProviderKind
         * @enum {string}
         */
        ProviderKind: "openai_compatible" | "anthropic" | "ollama";
        /** ProviderSummary */
        ProviderSummary: {
            /** Name */
            name: string;
            kind: components["schemas"]["ProviderKind"];
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /** Api Key Header */
            api_key_header?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /**
             * Has Api Key
             * @default false
             */
            has_api_key: boolean;
        };
        /** SetDefaultRequest */
        SetDefaultRequest: {
            /** Name */
            name: string;
        };
        /** SubscribeFeedRequest */
        SubscribeFeedRequest: {
            /** Url */
            url: string;
            /**
             * Sync
             * @default true
             */
            sync: boolean;
        };
        /** SummaryRequest */
        SummaryRequest: {
            /** Entry Id */
            entry_id: string;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
        };
        /** SummaryResult */
        SummaryResult: {
            /** Entry Id */
            entry_id: string;
            /** Summary Text */
            summary_text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "queued" | "running" | "success" | "failure" | "cancelled";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
        };
        /** SyncResult */
        SyncResult: {
            /** Feed Id */
            feed_id: string;
            /** Status */
            status: string;
            /** Fetched */
            fetched: number;
            /** Saved */
            saved: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Not Modified
             * @default false
             */
            not_modified: boolean;
        };
        /** Tag */
        Tag: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Usage Count */
            usage_count: number;
            /** Unread Count */
            unread_count: number;
        };
        /** TranslationRequest */
        TranslationRequest: {
            /** Entry Id */
            entry_id: string;
            /** Target Lang */
            target_lang: string;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
        };
        /** TranslationResult */
        TranslationResult: {
            /** Entry Id */
            entry_id: string;
            /** Target Lang */
            target_lang: string;
            /** Translation Html */
            translation_html: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "queued" | "running" | "success" | "failure" | "cancelled";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
        };
        /** UpdateProviderRequest */
        UpdateProviderRequest: {
            /** Name */
            name: string;
            /** Kind */
            kind?: string | null;
            /** Model */
            model?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Api Key Header */
            api_key_header?: string | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebPageResponse */
        WebPageResponse: {
            /** Article Id */
            article_id: string;
            /** Url */
            url: string;
            /** Final Url */
            final_url: string;
            /** Content Type */
            content_type?: string | null;
            /** Html */
            html: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_feeds_feeds_get: {
        parameters: {
            query?: {
                keyword?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feed_feeds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_feed_url_feeds_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_feed_feeds_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedValidationResult"];
                };
            };
        };
    };
    import_opml_file_feeds_opml_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OPMLImportResult"];
                };
            };
        };
    };
    export_opml_file_feeds_opml_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sync_all_feeds_sync_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"][];
                };
            };
        };
    };
    sync_one_feeds__feed_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_feed_feeds__feed_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tags_tags_get: {
        parameters: {
            query?: {
                keyword?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_providers_providers__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSummary"][];
                };
            };
        };
    };
    create_provider_providers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_by_name_providers__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSummary"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_provider_by_name_providers__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_provider_providers__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_default_provider_providers_default_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSummary"] | null;
                };
            };
        };
    };
    set_default_provider_providers_default_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDefaultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_provider_providers_test__name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entries_entries_get: {
        parameters: {
            query?: {
                feed_id?: string | null;
                keyword?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_entry_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_entry_read_state_entries__entry_id__read_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryReadStateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_entry_star_state_entries__entry_id__star_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryStarStateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clean_content_content_clean_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanContentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clean_stored_content_content_entries__article_id__clean_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_stored_web_page_content_entries__article_id__web_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_summary_agents_summary_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_article_agents_translation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
